# Generated by Django 4.1.4 on 2022-12-20 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Կատեգորիայի Անուն"),
                ),
                ("img", models.ImageField(upload_to="static/images")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="մեկնաբանության անուն"
                    ),
                ),
                ("comment", models.TextField(verbose_name="մեկնաբանություն")),
                ("postId", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Փոստի անվանում"),
                ),
                (
                    "img",
                    models.ImageField(
                        upload_to="static/images", verbose_name="Փոստի նկար"
                    ),
                ),
                (
                    "img_1",
                    models.ImageField(
                        upload_to="static/images", verbose_name="Փոստի փոքր նկարները"
                    ),
                ),
                (
                    "about",
                    models.CharField(max_length=250, verbose_name="Փոստի մասին հակիրճ"),
                ),
                ("about_detail", models.TextField(verbose_name="Փոստի մասին Ընդարձակ")),
                ("link", models.FileField(upload_to="static/files")),
                ("date", models.DateField(auto_now_add=True)),
                ("view", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.category",
                        verbose_name="Փոստի կատեգորիան",
                    ),
                ),
            ],
        ),
    ]
